version: "3.3"
services: 
  geotwin:
    build:
      args: 
        WORK_DIR: /go/src/github.com/MydroX/geotwin
    container_name: geotwin
    ports:
      - 8080:8080
      - 80:3000
    volumes: 
      - ../.:/go/src/github.com/MydroX/geotwin
    networks: 
      - geotwin

  geotwin-web:
    image: mydrox/geotwin-web:dev.1.0.0
    container_name: geotwin-web
    build:
      context: ../
      dockerfile: deploy/dev/web/Dockerfile
    ports: 
      - 8000:8000
    networks: 
      - geotwin

networks:
  geotwin:
    external: true
  